### PR TITLE
add posthtml-jade

### PR DESCRIPTION
**Pull request by hhsnopek**
oddly we were missing this...

### CODE REVIEW

**Comment by michaelcd** [comment]
I don't think posthtml-jade is used in spike-rooftop directly.

**Comment by hhsnopek** [comment]
oddly the tests throw an error without it installed

**Comment by michaelcd** [comment]
posthtml-jade is used in the test `app.js` files, so looks like it is required after all.

**Comment by hhsnopek** [comment]
yeah - it's referenced inside the fixtures

**Pull request merged**
